spring.application.name=pc-monitor
server.port=8080

# Disabilita banner superfluo
spring.main.banner-mode=console

# Log level: mostra solo INFO+ per il nostro package, WARNING per il resto
logging.level.root=WARN
logging.level.com.monitor.pcmonitor=INFO
